# Generated by Django 5.0.2 on 2024-02-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_of_cases', models.IntegerField(default=0)),
                ('is_traded', models.BooleanField(default=False)),
            ],
        ),
    ]
