# Generated by Django 5.0.2 on 2024-02-16 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam_requester', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
    ]
