# Generated by Django 5.0.2 on 2024-02-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam_requester', '0003_rename_id_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
